Merge v0.23.9
LogosFoundation/lotusd pull request #219
Opened 2021-09-01 22:24 UTC by schancel

2021-09-04 20:59 UTC, EyeOfPython requested changes

2021-09-04 20:59 UTC, EyeOfPython commented on src/qt/overviewpage.cpp
> +    // update the display unit, to not use the default ("XEC")
XPI

2021-09-04 20:59 UTC, EyeOfPython commented on src/qt/sendcoinsentry.cpp
> +    // update the display unit, to not use the default ("XEC")
XPI

2021-09-04 20:59 UTC, EyeOfPython commented on src/qt/test/paymentrequestdata.h
> +// 21,000,001,000,000 XEC)
XPI (adjust amount)

2021-09-04 20:59 UTC, EyeOfPython commented on src/rpc/mining.cpp
> +// NOTE: Unlike wallet RPC (which use XEC values), mining RPCs follow GBT (BIP
XPI

2021-09-04 20:59 UTC, EyeOfPython commented on src/wallet/test/coinselector_tests.cpp
> +        // we should get 1,000,000 XEC in 1 coin
XPI (adjust amount)

2021-09-04 20:59 UTC, EyeOfPython commented on src/wallet/test/coinselector_tests.cpp
> +        // we should get 2,000,000 XEC in 1 coin
XPI (adjust amount)

2021-09-04 20:59 UTC, EyeOfPython commented on test/functional/rpc_psbt.py
> +        # feeRate of 100,000 XEC / KB produces a total fee slightly below
XPI (adjust amount)

2021-09-04 20:59 UTC, EyeOfPython commented on test/functional/rpc_rawtransaction.py
> +        # Fee 10,000 satoshis, ~200 b transaction, fee rate should land around 50 sat/byte = 500 XEC/kB
XPI (adjust amount)

2021-09-04 20:59 UTC, EyeOfPython commented on test/functional/rpc_rawtransaction.py
> +        # Fee 2,000,000 satoshis, ~100 b transaction, fee rate should land around 20,000 sat/byte = 200,000 XEC/kB
XPI (adjust amount)

2021-09-04 20:59 UTC, EyeOfPython commented on test/functional/test_framework/util.py
> +            "Fee of {} XEC too low! (Should be {} XEC)".format(str(fee), str(target_fee)))
XPI

2021-09-04 20:59 UTC, EyeOfPython commented on test/functional/test_framework/util.py
> +            "Fee of {} XEC too high! (Should be {} XEC)".format(str(fee), str(target_fee)))
XPI

2021-09-04 20:59 UTC, EyeOfPython commented on test/functional/wallet_abandonconflict.py
> +        # Identify the 14,999,980 XEC output
XPI (adjust amount)

2021-09-04 20:59 UTC, EyeOfPython commented on test/functional/wallet_abandonconflict.py
> +        # Amount 14,999,980 XEC
XPI (adjust amount)

2021-09-04 20:59 UTC, EyeOfPython commented on test/functional/wallet_abandonconflict.py
> +        # Amount 10,000,000 XEC
XPI (adjust amount)

2021-09-04 20:59 UTC, EyeOfPython commented on test/functional/wallet_abandonconflict.py
> +        # Verify that B and C's 10,000,000 XEC outputs are available for
XPI (adjust amount)

2021-09-04 20:59 UTC, EyeOfPython commented on test/functional/wallet_abandonconflict.py
> +        # Invalidate the block with the double spend and B's 10,000,000 XEC
XPI (adjust amount)

2021-09-04 20:59 UTC, EyeOfPython commented on test/functional/wallet_avoidreuse.py
> +        # node 1 should now have a balance of 5MM (no dirty) or 15MM (including
adjust amount to XPI

2021-09-04 20:59 UTC, EyeOfPython commented on test/functional/wallet_import_rescan.py
> +import RPC call and node 0 sends XEC to it. Then other nodes import the
XPI

2021-09-04 20:59 UTC, EyeOfPython commented on test/functional/wallet_listsinceblock.py
> +        1. User 1 receives XEC in tx1 from utxo1 in block aa1.
XPI

2021-09-05 19:26 UTC, schancel commented on src/node/context.cpp
> +#include <txmempool.h>
@EyeOfPython This seems unnecessary?

2021-09-07 00:39 UTC, schancel commented on contrib/aur/bitcoin-abc-qt/PKGBUILD
> +pkgver=0.23.9
Guess this file goes back further. Needs to be deleted.

2021-09-11 20:39 UTC, schancel commented on contrib/aur/bitcoin-abc-qt/PKGBUILD
> +pkgver=0.23.9
Will delete before release 1.0.3. Merges are annoying to rebase.

2021-09-18 20:18 UTC, EyeOfPython commented on src/qt/test/paymentservertests.cpp
> +    // Payment request with amount overflow (amount is set to 21000001 XPI):
Shouldn't it be 2100000100 XPI?

2021-09-18 20:30 UTC, EyeOfPython approved these changes

2021-09-18 20:45 UTC, merged