New block header
LogosFoundation/lotusd pull request #85
Opened 2021-03-11 21:23 UTC by EyeOfPython

2021-03-13 00:01 UTC, schancel commented on src/primitives/block.cpp
>      return BlockHash(SerializeHash(*this));
This will need to be updated at some point for the hashing format you wanted.

2021-03-13 00:03 UTC, schancel commented on src/primitives/block.h
> +    std::vector<CBlockMetadataField> vMetadata;
Shouldn't this be in the header? Or are we doing it as a subtree out of the gate?

2021-03-13 00:09 UTC, schancel requested changes
This all makes sense. Is the goal here to just change the header in this commit, and then the hashing algorithm in another commit? I think that would make sense.

2021-03-13 04:33 UTC, EyeOfPython commented
I think having the hashing in this commit also makes more sense. I want the tests to pass, but then I'd have to redo all the PoW etc.

We should probably split the metadata part out though. Maybe always enforce it as the hash of '\0' for this PR.

2021-04-25 18:15 UTC, schancel commented
Closing, this has been superceeded.

2021-04-25 18:15 UTC, closed without merging